apiVersion: v1
kind: Pod
metadata:
  name: busyboxplus
spec:
  containers:
  - image: radial/busyboxplus:curl
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busyboxplus
  restartPolicy: Always
